### ISSUE TITLE
Module did not self-register

### ISSUE THREAD

**Issue by fskreuz** [gobblejs/gobble#111]
```
gobble: error starting gobble
>>>
Module did not self-register.
Error: Module did not self-register.
    at Error (native)
    at Object.Module._extensions..node (module.js:568:18)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (project\node_modules\pathwatcher\lib\main.js:6:13)
    at Object.<anonymous> (project\node_modules\pathwatcher\lib\main.js:218:4)
    at Module._compile (module.js:541:32)
```

Currently on Node 6 (trying out the new and shiny). But it only happens if you run `gobble` run via `npm` script. Launching `gobble` directly will work... sort of:

```
$ gobble
(node:4128) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
(node) v8::ObjectTemplate::Set() with non-primitive values is deprecated
(node) and will stop working in the next major release.

==== JS stack trace =========================================

Security context: 000001F5394C9FC9 <JS Object>#0#
    1: .node [module.js:568] [pc=000000E3B7FEEC04] (this=000001C1FF2126A1 <an Object with map 000003850E814F89>#1#,module=000003D420428E49 <a Module with map 000002F491617819>#2#,filename=000003D420428E21 <String[97]: node_modules\node-sass\vendor\win32-x64-48\binding.node>)
    2: load [module.js:~447] [pc=000000E3B814B056] (this=000003D420428E49 <a Module with map 000002F491617819>#2#,filename=000003D420428E21 <String[97]: node_modules\node-sass\vendor\win32-x64-48\binding.node>)
    3: tryModuleLoad(aka tryModuleLoad) [module.js:415] [pc=000000E3B7F3A61D] (this=000001F539404189 <undefined>,module=000003D420428E49 <a Module with map 000002F491617819>#2#,filename=000003D420428E21 <String[97]: node_modules\node-sass\vendor\win32-x64-48\binding.node>)
    4: _load [module.js:407] [pc=000000E3B7F35A62] (this=000001C1FF212659 <JS Function Module (SharedFunctionInfo 0000004964328311)>#3#,request=000003D420427401 <String[97]: node_modules\node-sass\vendor\win32-x64-48\binding.node>,parent=000003D42040A159 <a Module with map 000002F491617819>#4#,isMain=000001F539404299 <false>)
    5: require [module.js:~463] [pc=000000E3B7F8F10B] (this=000003D42040A159 <a Module with map 000002F491617819>#4#,path=000003D420427401 <String[97]: node_modules\node-sass\vendor\win32-x64-48\binding.node>)
    6: require(aka require) [internal/module.js:20] [pc=000000E3B7F45386] (this=000001F539404189 <undefined>,path=000003D420427401 <String[97]: node_modules\node-sass\vendor\win32-x64-48\binding.node>)
    7: /* anonymous */ [node_modules\node-sass\lib\index.js:23] [pc=000000E3B81E2901] (this=000003D42040A1A9 <an Object with map 000003C564D07B71>#5#,exports=000003D42040A1A9 <an Object with map 000003C564D07B71>#5#,require=000003D4204114A9 <JS Function require (SharedFunctionInfo 0000004964359B71)>#6#,module=000003D42040A159 <a Module with map 000002F491617819>#4#,__filename=000003D42040A131 <String[77]: node_modules\node-sass\lib\index.js>,__dirname=000003D420411441 <String[68]: node_modules\node-sass\lib>)
    8: _compile [module.js:541] [pc=000000E3B7F44064] (this=000003D42040A159 <a Module with map 000002F491617819>#4#,content=000003D42040B2E1 <Very long string[9855]>#7#,filename=000003D42040A131 <String[77]: node_modules\node-sass\lib\index.js>)
    9: .js [module.js:550] [pc=000000E3B7F3CB8B] (this=000001C1FF2126A1 <an Object with map 000003850E814F89>#1#,module=000003D42040A159 <a Module with map 000002F491617819>#4#,filename=000003D42040A131 <String[77]: node_modules\node-sass\lib\index.js>)
   10: load [module.js:~447] [pc=000000E3B814B056] (this=000003D42040A159 <a Module with map 000002F491617819>#4#,filename=000003D42040A131 <String[77]: node_modules\node-sass\lib\index.js>)
   11: tryModuleLoad(aka tryModuleLoad) [module.js:415] [pc=000000E3B7F3A61D] (this=000001F539404189 <undefined>,module=000003D42040A159 <a Module with map 000002F491617819>#4#,filename=000003D42040A131 <String[77]: node_modules\node-sass\lib\index.js>)
   12: _load [module.js:407] [pc=000000E3B7F35A62] (this=000001C1FF212659 <JS Function Module (SharedFunctionInfo 0000004964328311)>#3#,request=000000ECFBF18AE9 <String[9]: node-sass>,parent=000003D420369529 <a Module with map 000002F491617819>#8#,isMain=000001F539404299 <false>)
   13: require [module.js:~463] [pc=000000E3B7F8F10B] (this=000003D420369529 <a Module with map 000002F491617819>#8#,path=000000ECFBF18AE9 <String[9]: node-sass>)
   14: require(aka require) [internal/module.js:20] [pc=000000E3B7F45386] (this=000001F539404189 <undefined>,path=000000ECFBF18AE9 <String[9]: node-sass>)
   15: /* anonymous */ [node_modules\gobble-sass\index.js:3] [pc=000000E3B81CA957] (this=000003D420369579 <an Object with map 000003C564D07B71>#9#,exports=000003D420369579 <an Object with map 000003C564D07B71>#9#,require=000003D42036B0F1 <JS Function require (SharedFunctionInfo 0000004964359B71)>#10#,module=000003D420369529 <a Module with map 000002F491617819>#8#,__filename=000003D420369501 <String[75]: node_modules\gobble-sass\index.js>,__dirname=000003D42036B089 <String[66]: node_modules\gobble-sass>)
   16: _compile [module.js:541] [pc=000000E3B7F44064] (this=000003D420369529 <a Module with map 000002F491617819>#8#,content=000003D42036A4E9 <Very long string[1084]>#11#,filename=000003D420369501 <String[75]: node_modules\gobble-sass\index.js>)
   17: .js [module.js:550] [pc=000000E3B7F3CB8B] (this=000001C1FF2126A1 <an Object with map 000003850E814F89>#1#,module=000003D420369529 <a Module with map 000002F491617819>#8#,filename=000003D420369501 <String[75]: node_modules\gobble-sass\index.js>)
   18: load [module.js:~447] [pc=000000E3B814B056] (this=000003D420369529 <a Module with map 000002F491617819>#8#,filename=000003D420369501 <String[75]: node_modules\gobble-sass\index.js>)
   19: tryModuleLoad(aka tryModuleLoad) [module.js:415] [pc=000000E3B7F3A61D] (this=000001F539404189 <undefined>,module=000003D420369529 <a Module with map 000002F491617819>#8#,filename=000003D420369501 <String[75]: node_modules\gobble-sass\index.js>)
   20: _load [module.js:~381] [pc=000000E3B8072327] (this=000001C1FF212659 <JS Function Module (SharedFunctionInfo 0000004964328311)>#3#,request=000003D4203624C1 <String[11]: gobble-sass>,parent=0000027B33E10BC1 <a Module with map 000002F491617819>#12#,isMain=000001F539404299 <false>)
   21: require [module.js:~463] [pc=000000E3B7F8F10B] (this=0000027B33E10BC1 <a Module with map 000002F491617819>#12#,path=000003D4203624C1 <String[11]: gobble-sass>)
   22: /* anonymous */(aka /* anonymous */) [node_modules\require-relative\index.js:25] [pc=000000E3B81315A4] (this=000001F539404189 <undefined>,requested=000003D4203624C1 <String[11]: gobble-sass>,relativeTo=000001C1FF28C901 <String[41]: >)
   23: tryToLoad(aka tryToLoad) [node_modules\gobble\dist\gobble.js:1302] [pc=000000E3B81313E1] (this=000001F539404189 <undefined>,plugin=000000116D0796E9 <String[4]: sass>)
   24: transform [node_modules\gobble\dist\gobble.js:1267] [pc=000000E3B812E115] (this=0000027B33E10DD9 <a Source with map 000003850E815F59>#13#,fn=000000116D0796E9 <String[4]: sass>,userOptions=000003D420362481 <an Object with map 000002F4916BB799>#14#)
   25: /* anonymous */ [gobblefile.js:22] [pc=000000E3B8034A42] (this=0000023F1BC9DCC9 <an Object with map 000003C564D07B71>#15#,exports=0000023F1BC9DCC9 <an Object with map 000003C564D07B71>#15#,require=0000023F1BC9DBC1 <JS Function require (SharedFunctionInfo 0000004964359B71)>#16#,module=0000023F1BC9DB31 <a Module with map 000002F491617819>#17#,__filename=0000023F1BC9DC79 <String[55]: gobblefile.js>,__dirname=0000023F1BC9DC51 <String[41]: >)
   26: _compile [module.js:541] [pc=000000E3B7F44064] (this=0000023F1BC9DB31 <a Module with map 000002F491617819>#17#,content=0000023F1BC9E211 <Very long string[1169]>#18#,filename=0000023F1BC9DC79 <String[55]: gobblefile.js>)
   27: .js [module.js:550] [pc=000000E3B7F3CB8B] (this=000001C1FF2126A1 <an Object with map 000003850E814F89>#1#,module=0000023F1BC9DB31 <a Module with map 000002F491617819>#17#,filename=0000023F1BC9DC79 <String[55]: gobblefile.js>)
   28: load [module.js:~447] [pc=000000E3B7F3AAF2] (this=0000023F1BC9DB31 <a Module with map 000002F491617819>#17#,filename=0000023F1BC9DC79 <String[55]: gobblefile.js>)
   29: tryModuleLoad(aka tryModuleLoad) [module.js:415] [pc=000000E3B7F3A61D] (this=000001F539404189 <undefined>,module=0000023F1BC9DB31 <a Module with map 000002F491617819>#17#,filename=0000023F1BC9DC79 <String[55]: gobblefile.js>)
   30: _load [module.js:407] [pc=000000E3B7F35A62] (this=000001C1FF212659 <JS Function Module (SharedFunctionInfo 0000004964328311)>#3#,request=0000023F1BC9E731 <String[55]: gobblefile.js>,parent=0000023F1BC9E6E1 <a Module with map 000002F491617819>#19#,isMain=000001F539404299 <false>)
   31: require [module.js:~463] [pc=000000E3B7F8F10B] (this=0000023F1BC9E6E1 <a Module with map 000002F491617819>#19#,path=0000023F1BC9E731 <String[55]: gobblefile.js>)
   32: require(aka require) [internal/module.js:20] [pc=000000E3B7F45386] (this=000001F539404189 <undefined>,path=0000023F1BC9E731 <String[55]: gobblefile.js>)
   33: resume [npm\node_modules\gobble-cli\lib\watchOrServe.js:38] [pc=000000E3B8033ED1] (this=000001F5394E9141 <JS Global Object>#20#)
   34: /* anonymous */ [npm\node_modules\gobble-cli\lib\watchOrServe.js:8] [pc=000000E3B7FEC5C9] (this=000001F5394E9141 <JS Global Object>#20#,gobblefile=0000023F1BC9E731 <String[55]: gobblefile.js>,getTask=0000023F1BC9E8F1 <JS Function (SharedFunctionInfo 00000381097DEE91)>#21#)
   35: /* anonymous */ [npm\node_modules\gobble-cli\lib\serve.js:6] [pc=000000E3B7FEC060] (this=000001F5394E9141 <JS Global Object>#20#,command=0000023F1BC9E971 <an Object with map 000002F49165EBF9>#22#,gobblefile=0000023F1BC9E731 <String[55]: gobblefile.js>)
   36: /* anonymous */ [npm\node_modules\gobble-cli\lib\index.js:126] [pc=000000E3B7FE6068] (this=0000023F1BC9EA49 <a Liftoff with map 000002F49165F4E9>#23#,env=0000023F1BC9E9F9 <an Object with map 000002F491663271>#24#)
   37: /* anonymous */ [npm\node_modules\gobble-cli\node_modules\liftoff\index.js:193] [pc=000000E3B7FC0400] (this=0000023F1BC9EA49 <a Liftoff with map 000002F49165F4E9>#23#,ready=000001F539404231 <true>,child=000001F5394E52E1 <a process with map 000003C564D10D89>#25#)
   38: /* anonymous */ [npm\node_modules\gobble-cli\node_modules\flagged-respawn\index.js:17] [pc=000000E3B7FC07D5] (this=000001F5394E9141 <JS Global Object>#20#,flags=0000023F1BC9EB91 <JS Array[389]>#26#,argv=0000029F1F90D5E9 <JS Array[2]>#27#,execute=0000023F1BC9EB31 <JS BoundFunction bound  (BoundTargetFunction 0000023F1BC9EAB1)>#28#)
   39: /* anonymous */ [npm\node_modules\gobble-cli\node_modules\liftoff\index.js:185] [pc=000000E3B7FBD7B0] (this=0000023F1BC9EA49 <a Liftoff with map 000002F49165F4E9>#23#,err=000001F539404101 <null>,flags=0000023F1BC9EB91 <JS Array[389]>#26#)
   40: /* anonymous */ [npm\node_modules\gobble-cli\node_modules\liftoff\index.js:159] [pc=000000E3B7FC0122] (this=000001F5394E9141 <JS Global Object>#20#,err=000001F539404101 <null>,flags=0000023F1BC9EB91 <JS Array[389]>#26#)
   41: /* anonymous */ [npm\node_modules\gobble-cli\node_modules\v8flags\index.js:108] [pc=000000E3B7FBFFA5] (this=000001F5394E9141 <JS Global Object>#20#,openErr=000001F539404101 <null>,result=0000023F1BC9EB91 <JS Array[389]>#26#)
   42: /* anonymous */ [npm\node_modules\gobble-cli\node_modules\v8flags\index.js:36] [pc=000000E3B7FBFE63] (this=000001F5394E9141 <JS Global Object>#20#,err=000001F539404101 <null>,fd=0000023F1BC9EB91 <JS Array[389]>#26#)
   43: /* anonymous */ [npm\node_modules\gobble-cli\node_modules\v8flags\index.js:47] [pc=000000E3B7FBFBE0] (this=000001F5394E9141 <JS Global Object>#20#)
   44: _combinedTickCallback(aka _combinedTickCallback) [internal/process/next_tick.js:67] [pc=000000E3B7FBF872] (this=000001F539404189 <undefined>,args=000001F539404189 <undefined>,callback=0000023F1BC9EDC1 <JS Function (SharedFunctionInfo 00000381097C42B9)>#29#)
   45: _tickCallback [internal/process/next_tick.js:98] [pc=000000E3B7FBF50B] (this=000001F5394E52E1 <a process with map 000003C564D10D89>#25#)
   46: runMain [module.js:577] [pc=000000E3B7F3558D] (this=000001C1FF212659 <JS Function Module (SharedFunctionInfo 0000004964328311)>#3#)
   47: startup(aka startup) [node.js:159] [pc=000000E3B7E40A3E] (this=000001F539404189 <undefined>)
   48: /* anonymous */(aka /* anonymous */) [node.js:444] [pc=000000E3B7E3E6D2] (this=000001F539404101 <null>,process=000001F5394E52E1 <a process with map 000003C564D10D89>#25#)
=====================
# Gobble continues to run normally after this
```

For this one, I'm not sure if it's gobble-related but just a heads up.

**Comment by Rich-Harris** [comment]
Is this still happening with latest gobble and gobble-cli?

**Comment by fskreuz** [comment]
Running `gobble` directly gives me just this, but otherwise, works fine.
```
(node:7164) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
```
Running it via npm still gives the same `Module did not self-register.` error tho.

**Comment by fskreuz** [comment]
Closing. Doesn't appear to happen anymore.
