### ISSUE TITLE
More broken gobble

### ISSUE THREAD

**Issue by martypdx** [gobblejs/gobble#60]
Dead in the water using `gobble-cli 0.4.0`. Have `rm -rf node_modules` as well as same on gobble-cli in global bin. :(

```sh
RangeError: Invalid array length
    at /Users/marty/npm/lib/node_modules/gobble-cli/lib/utils/logger.js:54:19
    at Array.forEach (native)
    at indent (/Users/marty/npm/lib/node_modules/gobble-cli/lib/utils/logger.js:50:8)
    at warn (/Users/marty/npm/lib/node_modules/gobble-cli/lib/utils/logger.js:30:26)
    at Object.logger.warn (/Users/marty/npm/lib/node_modules/gobble-cli/lib/utils/logger.js:349:4)
    at Liftoff.<anonymous> (/Users/marty/npm/lib/node_modules/gobble-cli/lib/index.js:88:11)
    at Liftoff.<anonymous> (/Users/marty/npm/lib/node_modules/gobble-cli/node_modules/liftoff/index.js:159:12)
    at module.exports (/Users/marty/npm/lib/node_modules/gobble-cli/node_modules/liftoff/node_modules/flagged-respawn/index.js:17:3)
    at Liftoff.launch (/Users/marty/npm/lib/node_modules/gobble-cli/node_modules/liftoff/index.js:152:5)
    at Object.<anonymous> (/Users/marty/npm/lib/node_modules/gobble-cli/lib/index.js:68:6)
```

**Comment by Rich-Harris** [comment]
Oh no! Sorry. At what point are you getting that error - immediately after running `gobble`, or is it related to a specific transformation? Is it failing with a specific repo or all of them?

**Comment by martypdx** [comment]
No worries, I'm sure we'll get it figured out. I went back to 0.3.5, so not stuck. 

But will try out from scratch to see if it's just that repo. Are there breaking changes in gobblefile I need to look out for?

**Comment by Rich-Harris** [comment]
No, all recent changes are bug fixes, ironically...

**Comment by Rich-Harris** [comment]
Well, I just ran into the same bug. Looks like gobble-cli is at fault - I'll close this in favour of https://github.com/gobblejs/gobble-cli/issues/13
