### ISSUE TITLE
resolvePathAndOptions is not defined in merge pass on Windows

### ISSUE THREAD

**Issue by Bobris** [gobblejs/gobble#77]
Maybe it is problem in gobble-esperanto-bundle which has dependency on old sander???

Output:

```
c:\Research\sandbox>gobble watch out
gobble: 01-esperantoBundle done in 70ms
∙∙∙∙∙∙∙ 02-merge running...
gobble: resolvePathAndOptions is not defined
>>>
ReferenceError: resolvePathAndOptions is not defined
    at Object.symlinkOrCopy (c:\Research\sandbox\node_modules\gobble\node_module
s\sander\src\extraMethods\symlinkOrCopy.js:10:55)
    at link (c:\Research\sandbox\src\nodes\Merger.js:52:1)
    at lib$es6$promise$$internal$$tryCatch (c:\Research\sandbox\node_modules\gob
ble-esperanto-bundle\node_modules\sander\node_modules\es6-promise\dist\es6-promi
se.js:319:16)
    at lib$es6$promise$$internal$$invokeCallback (c:\Research\sandbox\node_modul
es\gobble-esperanto-bundle\node_modules\sander\node_modules\es6-promise\dist\es6
-promise.js:331:17)
    at lib$es6$promise$$internal$$publish (c:\Research\sandbox\node_modules\gobb
le-esperanto-bundle\node_modules\sander\node_modules\es6-promise\dist\es6-promis
e.js:302:11)
    at lib$es6$promise$$internal$$publishRejection (c:\Research\sandbox\node_mod
ules\gobble-esperanto-bundle\node_modules\sander\node_modules\es6-promise\dist\e
s6-promise.js:252:7)
    at lib$es6$promise$asap$$flush (c:\Research\sandbox\node_modules\gobble-espe
ranto-bundle\node_modules\sander\node_modules\es6-promise\dist\es6-promise.js:11
3:9)
    at process._tickCallback (node.js:355:11)
```

**Comment by clintwood** [comment]
Same error here - using `gobble build _out`
```
// this works
module.exports = gobble('./_build').transform( 'esperanto-bundle', {
      strict: true,
      type: 'cjs',
      entry: 'builder.js'
    });

// this doesn't (using array)
module.exports = gobble([
    gobble('./_build').transform( 'esperanto-bundle', {
      strict: true,
      type: 'cjs',
      entry: 'builder.js'
    })
]);

// nor this (esperanto plugin)
module.exports = gobble('./_build/test').transform( 'esperanto', {
      strict: true,
      type: 'cjs'
    });
```
`gobble-cli version 0.4.2`
`local gobble: 0.10.1`
`gobble-esperanto: 0.3.0`
`gobble-esperanto-bundle: 0.2.0`

**Comment by clintwood** [comment]
@Rich-Harris, Ping!

Really keen to use this (Windows)... Will fork for now so that it pulls in Rich-Harris/sander/pull/4, but I'm concerned that a number of your repos that I'm using also have `sander` as a dep which may have side effects...

**Comment by Rich-Harris** [comment]
Sorry for the slow turnaround on this @Bobris - @clintwood sent a patch to sander which hopefully fixes this issue. If you update/reinstall gobble and gobble-esperanto-bundle, hopefully it'll work... let me know either way!

**Comment by Bobris** [comment]
Thanks a lot. I can confirm it works now.

**Comment by clintwood** [comment]
Awesome, thanks!!!
