### ISSUE TITLE
Strange ENOENT error related to sourcemaps

### ISSUE THREAD

**Issue by msegado** [gobblejs/gobble#82]
Hi,

Not sure if this is a gobble issue or something I'm doing wrong, but I'm getting a very peculiar error when building (which I'm assuming happens when I try to include and move a `jspm_packages` folder in my project):

```
gobble: ENOENT, open                                                           
        '/home/project/.gobble-build/08-merge/1/jspm_packages/' +  
        sourceMap : '');'                                                      
>>>
Error: ENOENT, open '/home/project/.gobble-build/08-merge/1/jspm_packages/' + sourceMap : '');'
    at Error (native)
<<<
```

Here's my gobblefile for reference:

```
var gobble = require( 'gobble' );

module.exports = gobble([
  gobble('styles')
    .transform('sass', {
      src: 'main.scss',
      dest: 'main.css'
    })
    .transform('autoprefixer'),

  gobble('lib')
    .transform('babel', {
      "optional": ["runtime"]
    })
    .moveTo('lib'),

  gobble('config.js'),
  gobble('jspm_packages').moveTo('jspm_packages'),

  gobble('html')
    .transform('replace', {
      systemjs_path: 'jspm_packages/system.js',
      configjs_path: 'config.js',
      css_path: 'main.css'
    })
]);
```

Any thoughts?

**Comment by Mouvedia** [comment]
Did the the `jspm_packages` directory exist?

**Comment by msegado** [comment]
@Mouvedia Yup, it exists. On thinking about it, I expect the problem is related to some other "Unexpected token" errors I was getting. Here's the full output:

```
msegado:~/projectname$ ./node_modules/.bin/gobble build dist -f
gobble: build started                                                          
gobble: 01-sass done in 180ms                                          
gobble: 02-autoprefixer done in 1996ms                                 
gobble: 03-babel done in 1248ms                                        
gobble: 04-moveTo done in 8ms                                          
gobble: 06-moveTo done in 116ms                                        
gobble: 07-replace done in 15ms                                        
gobble: 08-merge done in 7ms                                           

gobble: ENOENT, open                                                           
        '/home/msegado/projectname/.gobble-build/08-merge/1/jspm_packages/' +  
        sourceMap : '');'                                                      
>>>
Error: ENOENT, open '/home/msegado/projectname/.gobble-build/08-merge/1/jspm_packages/' + sourceMap : '');'
    at Error (native)
<<<


gobble: ENOENT, open                                                           
        '/home/msegado/projectname/.gobble-build/08-merge/1/jspm_packages/' +  
        sourceMap : '');'                                                      
>>>
Error: ENOENT, open '/home/msegado/projectname/.gobble-build/08-merge/1/jspm_packages/' + sourceMap : '');'
    at Error (native)
<<<


gobble: Unexpected token �                                                     
>>>
SyntaxError: Unexpected token �
    at Object.parse (native)
    at getMapFromUrl (/home/msegado/projectname/node_modules/gobble/node_modules/sorcery/dist/sorcery.js:496:18)
    at getMap (/home/msegado/projectname/node_modules/gobble/node_modules/sorcery/dist/sorcery.js:545:10)
    at /home/msegado/projectname/node_modules/gobble/node_modules/sorcery/dist/sorcery.js:598:11
    at lib$es6$promise$$internal$$tryCatch (/home/msegado/projectname/node_modules/gobble/node_modules/sorcery/node_modules/sander/node_modules/es6-promise/dist/es6-promise.js:331:16)
    at lib$es6$promise$$internal$$invokeCallback (/home/msegado/projectname/node_modules/gobble/node_modules/sorcery/node_modules/sander/node_modules/es6-promise/dist/es6-promise.js:343:17)
    at lib$es6$promise$$internal$$publish (/home/msegado/projectname/node_modules/gobble/node_modules/sorcery/node_modules/sander/node_modules/es6-promise/dist/es6-promise.js:314:11)
    at lib$es6$promise$asap$$flush (/home/msegado/projectname/node_modules/gobble/node_modules/sorcery/node_modules/sander/node_modules/es6-promise/dist/es6-promise.js:125:9)
    at process._tickCallback (node.js:355:11)
<<<


gobble: Unexpected token �                                                     
>>>
SyntaxError: Unexpected token �
    at Object.parse (native)
    at getMapFromUrl (/home/msegado/projectname/node_modules/gobble/node_modules/sorcery/dist/sorcery.js:496:18)
    at getMap (/home/msegado/projectname/node_modules/gobble/node_modules/sorcery/dist/sorcery.js:545:10)
    at /home/msegado/projectname/node_modules/gobble/node_modules/sorcery/dist/sorcery.js:598:11
    at lib$es6$promise$$internal$$tryCatch (/home/msegado/projectname/node_modules/gobble/node_modules/sorcery/node_modules/sander/node_modules/es6-promise/dist/es6-promise.js:331:16)
    at lib$es6$promise$$internal$$invokeCallback (/home/msegado/projectname/node_modules/gobble/node_modules/sorcery/node_modules/sander/node_modules/es6-promise/dist/es6-promise.js:343:17)
    at lib$es6$promise$$internal$$publish (/home/msegado/projectname/node_modules/gobble/node_modules/sorcery/node_modules/sander/node_modules/es6-promise/dist/es6-promise.js:314:11)
    at lib$es6$promise$asap$$flush (/home/msegado/projectname/node_modules/gobble/node_modules/sorcery/node_modules/sander/node_modules/es6-promise/dist/es6-promise.js:125:9)
    at process._tickCallback (node.js:355:11)
<<<


gobble: ENOENT, open                                                           
        '/home/msegado/projectname/.gobble-build/08-merge/1/jspm_packages/npm/simulant@0.1.5/dist/simulant.js.map'
>>>
Error: ENOENT, open '/home/msegado/projectname/.gobble-build/08-merge/1/jspm_packages/npm/simulant@0.1.5/dist/simulant.js.map'
    at Error (native)
<<<

gobble: built to dist in 7531ms  
```

(Note that the last error is different and is due to an actual missing sourcemap: Rich-Harris/simulant#8)

**Comment by msegado** [comment]
Interesting; I no longer get the original error in my current build setup (which I think uses a newer version of Gobble). I'm going to assume it was fixed at some point and close this issue, and open a different one for the other errors.

**Comment by msegado** [comment]
(this seems to be a Sorcery error and not a Gobble error; opened an issue over there with more details)
